<?php

namespace MCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SearchFilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchFilmRepository extends EntityRepository
{
}
