<?php

namespace MCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
    public function getDescSessions()
    {
        $query = $this->createQueryBuilder('a');
        $query->orderBy('a.id', 'DESC');
        return $query
            ->getQuery()
            ->getResult();

    }

    public function sessionByFilm($id)
    {
        $query = $this->createQueryBuilder('s');
        $query
            ->innerJoin('s.film', 'f')
            ->where('f.id = :id')
            ->setParameter('id', $id);
        $query->orderBy('s.id', 'DESC');
        return $query
            ->getQuery()
            ->getResult();
    }

    public function search($search)
    {
        $em = $this->getEntityManager();
        if ($search != null) {
            $query = $em->createQuery("
                    SELECT s
                    FROM MCBundle:Session s
                    JOIN s.film f
                    WHERE f.title LIKE :search OR f.synopsis LIKE :search OR f.originalTitle LIKE :search OR f.actors LIKE :search")
                ->setParameter('search', '%' . $search . '%');
        } else {
            $query = $em->createQuery("SELECT s FROM MCBundle:Session s");
        }
        return $query;
    }

    public function findParticipant($creator)
    {

        $em = $this->getEntityManager();
        $query = $em->createQuery("
                    SELECT p
                    FROM MCBundle:Session s
                    JOIN s.creator c
                    JOIN  MCBundle:Participant p
                    WHERE c.id = :creator AND s.id = p.session")
            ->setParameter('creator', $creator);

        return $query->getResult();
//                            JOIN s.creator p

    }


}
