<?php

namespace MCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
    public function getDescSessions()
    {
        $query = $this->createQueryBuilder('a');
        $query->orderBy('a.id', 'DESC');
        return $query
            ->getQuery()
            ->getResult();

    }

    public function sessionByFilm($id)
    {
        $query = $this->createQueryBuilder('s');
        $query
            ->innerJoin('s.film', 'f')
            ->where('f.id = :id')
            ->setParameter('id', $id);
        $query->orderBy('s.id', 'DESC');
        return $query
            ->getQuery()
            ->getResult();
    }
}
