<?php

namespace MCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMaterialRepository extends EntityRepository
{
}
