<?php

namespace MCBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeNoteRepository extends EntityRepository
{
}
