# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    encoders:
        UserBundle\Entity\User: sha512
    providers:
        main_providers:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern:   ^/session/login$
            anonymous: true 
        main:
            pattern:   ^/session
            anonymous: false
            provider:  main_providers
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /
            logout:
                path:   fos_user_security_logout
                target: /login
            remember_me:
                key: %secret%
                lifetime: 1800 # 30 min
                path: /login
         
    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/session/admin, roles: ROLE_ADMIN }
        - { path: ^/session/admin, roles: ROLE_SUPER_ADMIN }
