security:
    encoders:
          FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        main_providers:
            id: fos_user.user_provider.username          

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern:   ^/login$
            anonymous: true 
        main:
            pattern:   ^/
            anonymous: true
            provider:  main_providers
            
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
#                success_handler: authentication_handler
#                failure_handler: authentication_handler
#                default_target_path: /user
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                key:   %secret%
                lifetime: 1800 # 30 min
                path: /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting/, role: ROLE_USER }
        - { path: ^/backoffice/, role: ROLE_USER }
        - { path: ^/profile/, role: ROLE_USER }
        - { path: ^/seance/participate/, role: ROLE_USER }
        - { path: ^/seances/add/form, role: ROLE_USER }
        - { path: ^/seances/comment/form, role: ROLE_USER }
#        - { path: ^/account/, role:  ROLE_SUPER_ADMIN}
#        - { path: ^/account/, role: ROLE_ADMIN, requires_channel: https }
