# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    allo_throw_exceptions: true
#    allocine_secret_key: 29d185d98c984a359e6e6f26a0474269
#    allo_utf8_decode: true
#    allo_auto_correct_apostrophes: true
#    allo_partner: 100043982026
#    allo_default_url_api: api.allocine.fr
#    allo_default_url_images: images.allocine.fr

services:
    fos_user.doctrine_registry:
        alias: doctrine
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#    mc_allo_data:
#        class: MCBundle\Service\AlloData        
#    mc_allo_image:
#        class: MCBundle\Service\AlloImage
    
#    mc_allo_helper:
#        class: MCBundle\Service\AlloHelper
#        arguments: [ "%allo_throw_exceptions%","%allocine_secret_key%","%allo_utf8_decode%"]
##          - %allo_throw_exceptions%
##          - %allocine_secret_key%
##          - %allo_utf8_decode%
##          - %allo_auto_correct_apostrophes%
##          - %allo_partner%
##          - %allo_default_url_api%
##          - %allo_default_url_images%
