<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function checkSession($username, $password)
    {
        $query = $this->createQueryBuilder('a');
        $query->where('a.username = :username AND a.password=:password')
            ->setParameter('username', $username)
            ->setParameter('password', $password)
            ->setMaxResults(1);
        
        return $query
            ->getQuery()
            ->getResult();
    }
}
