mc_homepage:
    path:     /
    defaults: { _controller: MCBundle:MatiesChill:index }
mc_sessions:
    path:     /sessions
    defaults: { _controller: MCBundle:MatiesChill:session }
mc_films:
    path:     /films
    defaults: { _controller: MCBundle:MatiesChill:film }
mc_search_film:
    path:     /search
    defaults: { _controller: MCBundle:MatiesChill:searchFilm }
    
mc_search_films:
    path:     /search/{film}
    defaults: { _controller: MCBundle:MatiesChill:films }

mc_film_all_publish:
    path:     /webservice
    defaults: { _controller: MCBundle:Film:filmAll }

mc_film_all_publishs:
    path:     /webservice/films
    defaults: { _controller: MCBundle:Film:filmAll }
    
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"