

#  Allocine
mc_film_search_allocine:
    path:     /search/allocine/{keyword}
    defaults: { _controller: MCBundle:Film:searchAllocineFilm }  
  
mc_film_get_allocine:
    path:     /film/allocine/{code}
    defaults: { _controller: MCBundle:Film:getFilmAllocine }


mc_web_film_all:
    path:     /ressources/films
    defaults: { _controller: MCBundle:Film:allMovie }

mc_web_film_get:
    path:     /ressources/film/get/{id}
    defaults: { _controller: MCBundle:Film:getMovie }
    
mc_web_film_delete:
    path:     /ressources/film/delete/{id}
    defaults: { _controller: MCBundle:Film:removeMovie }

mc_web_film_add:
    path:     /ressources/film/add/{id}
    defaults: { _controller: MCBundle:Film:addMovie }


 #Rest Api
api-film:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestFilmController
    
api-session:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestSessionController
api-user:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestUserController
api-genre:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestGenreController
api-rest:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestController

#Back office

mc_themes:
    resource: MCBundle\Controller\MCController
    type:     annotation
    prefix:   /
    
mc_session:
    resource: MCBundle\Controller\SessionController
    type:     annotation
    prefix:   /
    
mc_film:
    resource: MCBundle\Controller\FilmController
    type:     annotation
    prefix:   /

mc_backoffice:
    resource: MCBundle\Controller\BackOffice\SessionBOController
    type:     annotation
    prefix:   /backoffice