mc_homepage:
    path:     /
    defaults: { _controller: MCBundle:MatiesChill:index }
mc_sessions:
    path:     /sessions
    defaults: { _controller: MCBundle:MatiesChill:session }
mc_films:
    path:     /films
    defaults: { _controller: MCBundle:MatiesChill:film }
    
mc_search_film:
    path:     /search
    defaults: { _controller: MCBundle:MatiesChill:searchField }
  
mc_film_search_allocine:
    path:     /search/allocine/{keyword}
    defaults: { _controller: MCBundle:MatiesChill:searchAllocineFilm }  
  
mc_film_get_allocine:
    path:     /film/allocine/{code}
    defaults: { _controller: MCBundle:MatiesChill:getFilmAllocine }
#WebService
mc_web_film_all:
    path:     /ressources/films
    defaults: { _controller: MCBundle:Film:allMovie }

mc_web_film_get:
    path:     /ressources/film/get/{id}
    defaults: { _controller: MCBundle:Film:getMovie }
    
mc_web_film_delete:
    path:     /ressources/film/delete/{id}
    defaults: { _controller: MCBundle:Film:removeMovie }

mc_web_film_add:
    path:     /ressources/film/add/{id}
    defaults: { _controller: MCBundle:Film:addMovie }
 
 #Rest Api
api:
    type:  rest
    resource: MCBundle\Controller\MCRestController
 