

#  Allocine

 #Rest Api
api-film:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestFilmController
    
api-seance:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestSeanceController
api-user:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestUserController
api-genre:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestGenreController
api-rest:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestController

#Back office

mc_themes:
    resource: MCBundle\Controller\MCController
    type:     annotation
    prefix:   /mc
    
mc_seance:
    resource: MCBundle\Controller\SeanceController
    type:     annotation
    prefix:   /mc
    
mc_film:
    resource: MCBundle\Controller\FilmController
    type:     annotation
    prefix:   /mc
    
mc_coming_soon:
    resource: MCBundle\Controller\ComingSoonController
    type:     annotation
    prefix:   /

mc_backoffice:
    resource: MCBundle\Controller\BackOffice\SeanceBOController
    type:     annotation
    prefix:   /backoffice