mc_homepage:
    path:     /
    defaults: { _controller: MCBundle:MatiesChill:index }

# Session
mc_session_add:
    path:     /sessions/add
    defaults: { _controller: MCBundle:Session:addSession }
 
mc_session_home:
    path:     /sessions
    defaults: { _controller: MCBundle:Session:index }

#Films
mc_film_home:
    path:     /films
    defaults: { _controller: MCBundle:Film:index }
    
mc_film_action:
    path:     /films/{action}
    defaults: { _controller: MCBundle:Film:getFilm }
    
mc_film_view:
    path:     /film/view/{slug}.html
    defaults: { _controller: MCBundle:Film:viewFilm }
mc_film_search:
    path:     /film/search/{keyword}
    defaults: { _controller: MCBundle:Film:searchFilm }
    
mc_film_add:
    path:     /film/add.html
    defaults: { _controller: MCBundle:Film:addFilm }
mc_film_edit:
    path:     /film/edit
    defaults: { _controller: MCBundle:Film:addFilm }
mc_film_remove:
    path:     /film/{id}/remove.html
    defaults: { _controller: MCBundle:Film:removeFilmField }

#  Allocine
mc_film_search_allocine:
    path:     /search/allocine/{keyword}
    defaults: { _controller: MCBundle:Film:searchAllocineFilm }  
  
mc_film_get_allocine:
    path:     /film/allocine/{code}
    defaults: { _controller: MCBundle:Film:getFilmAllocine }

#search field
mc_search_field:
    path:     /search-field
    defaults: { _controller: MCBundle:MatiesChill:searchField }
  
#WebService
mc_web_film_all:
    path:     /ressources/films
    defaults: { _controller: MCBundle:Film:allMovie }

mc_web_film_get:
    path:     /ressources/film/get/{id}
    defaults: { _controller: MCBundle:Film:getMovie }
    
mc_web_film_delete:
    path:     /ressources/film/delete/{id}
    defaults: { _controller: MCBundle:Film:removeMovie }

mc_web_film_add:
    path:     /ressources/film/add/{id}
    defaults: { _controller: MCBundle:Film:addMovie }


 #Rest Api
api-film:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestFilmController
    
api-session:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestSessionController
api-user:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestUserController
api-genre:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestGenreController
api-rest:
    type:  rest
    prefix: /api/
    resource: MCBundle\Controller\Rest\MCRestController

#Back office
backoffice-session:
    prefix: /backoffice/
    resource: MCBundle\Controller\BackOffice\SessionBOController

