mc_homepage:
    path:     /
    defaults: { _controller: MCBundle:MatiesChill:index }
mc_sessions:
    path:     /sessions
    defaults: { _controller: MCBundle:MatiesChill:session }
mc_films:
    path:     /films
    defaults: { _controller: MCBundle:MatiesChill:film }
mc_search_film:
    path:     /search/{keyword}
    defaults: { _controller: MCBundle:MatiesChill:searchFilm }
#    requirements:
#        _method: GET 